In [2]:
import sys

In [2]:
!conda install --yes --prefix {sys.prefix} -c conda-forge python-twitter

Solving environment: ...working... done

## Package Plan ##

  environment location: D:\Anaconda3

  added / updated specs:
    - python-twitter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-twitter-3.5         |             py_0          58 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          58 KB

The following NEW packages will be INSTALLED:

  python-twitter     conda-forge/noarch::python-twitter-3.5-py_0




python-twitter-3.5   | 58 KB     |            |   0% 
python-twitter-3.5   | 58 KB     | ##7        |  28% 
python-twitter-3.5   | 58 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


In [5]:
# reading lines from twitter text file for secrets

from pathlib import Path

keyFolder = Path("C://develop/keys/social_media_analytics/")
twitterKeyFile = keyFolder / "twitter.txt"

with open(twitterKeyFile) as file:
    content = file.readlines()

consumerKey = content[0].split(':')[1].strip()
consumerSecret = content[1].split(':')[1].strip()
accessTokenKey = content[2].split(':')[1].strip()
accessTokenSecret = content[3].split(':')[1].strip()

In [113]:
# establishing the actual api

import twitter

api = twitter.Api(
    consumer_key=consumerKey,
    consumer_secret=consumerSecret,
    access_token_key=accessTokenKey,
    access_token_secret=accessTokenSecret,
    sleep_on_rate_limit=True
)

In [114]:
print(api.VerifyCredentials())

{"created_at": "Thu Sep 05 03:05:57 +0000 2019", "default_profile": true, "default_profile_image": true, "description": "They call me the copper cat", "followers_count": 1, "friends_count": 2, "id": 1169446302729547782, "id_str": "1169446302729547782", "name": "Kanye North", "profile_background_color": "F5F8FA", "profile_image_url": "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png", "profile_image_url_https": "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png", "profile_link_color": "1DA1F2", "profile_sidebar_border_color": "C0DEED", "profile_sidebar_fill_color": "DDEEF6", "profile_text_color": "333333", "profile_use_background_image": true, "screen_name": "RealKanyeNorth1", "status": {"created_at": "Fri Nov 15 02:33:33 +0000 2019", "id": 1195167924992036864, "id_str": "1195167924992036864", "in_reply_to_screen_name": "BSatmary", "in_reply_to_status_id": 1174834418743218177, "in_reply_to_user_id": 505318888, "lang": "en", "sour

In [117]:
# test

api.GetFriends()

[User(ID=505318888, ScreenName=BSatmary), User(ID=48028397, ScreenName=Marmot)]

In [103]:
import time

# going to take the top 15 human accounts and see if they are following any of each other and use race and sex as traits

###### this is what is left to search for
screenNames = ['barackobama',
               'katyperry',
               'justinbieber',
               'rihanna',
               'taylorswift13',
               'cristiano',
               'ladygaga',
               'theellenshow',
               'arianagrande',
               'realdonaldtrump',
               'jtimberlake',
               'kimkardashian',
               'selenagomez',
               'britneyspears',
               'shakira']


users = [813286, 21447363, 27260086, 79293791, 17919972,
         155659213, 14230524, 15846407, 34507480, 25073877,
         26565946, 25365536, 23375688, 16409683, 44409004]

# we are doing this to get all of the user ids
#for name in screenNames:
    #users.append(api.GetUser(screen_name = name))
    #time.sleep(30) # we will get denied if we do too many requests in too short of time, but it's fine


# use this with a list of user ids to minimize calls
fullUsers = api.UsersLookup(user_id=users)

In [170]:
# we have all the individual user information

# list of users by index
userIntToScreenNames = []
[userIntToScreenNames.append(u.screen_name) for u in fullUsers]

# dictionary of names to their index
userScreenNamesToIndex = {}
i = 0
for key in userIntToScreenNames:
    userScreenNamesToIndex[key] = i
    i += 1

for key in userScreenNamesToIndex:
    print(key)
    print(userScreenNamesToIndex[key])

# print(api.LookupFriendship(user_id=users))

# https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show

BarackObama
0
katyperry
1
justinbieber
2
rihanna
3
taylorswift13
4
Cristiano
5
ladygaga
6
TheEllenShow
7
ArianaGrande
8
realDonaldTrump
9
jtimberlake
10
KimKardashian
11
selenagomez
12
britneyspears
13
shakira
14


In [88]:
for tweet in tweets:
    print("--- new tweet ---")
    print(tweet)


--- new tweet ---
{"created_at": "Wed Nov 13 17:18:36 +0000 2019", "favorite_count": 354, "hashtags": [{"text": "IGNORANtForever"}], "id": 1194665881260961792, "id_str": "1194665881260961792", "lang": "en", "media": [{"display_url": "pic.twitter.com/Cv2D3tWaBH", "expanded_url": "https://twitter.com/SAINtJHN/status/1194665881260961792/photo/1", "id": 1194664677697052673, "media_url": "http://pbs.twimg.com/media/EJRNMdvW4AE-EJF.jpg", "media_url_https": "https://pbs.twimg.com/media/EJRNMdvW4AE-EJF.jpg", "sizes": {"large": {"h": 2048, "resize": "fit", "w": 1364}, "medium": {"h": 1200, "resize": "fit", "w": 799}, "small": {"h": 680, "resize": "fit", "w": 453}, "thumb": {"h": 150, "resize": "crop", "w": 150}}, "type": "photo", "url": "https://t.co/Cv2D3tWaBH"}, {"display_url": "pic.twitter.com/Cv2D3tWaBH", "expanded_url": "https://twitter.com/SAINtJHN/status/1194665881260961792/photo/1", "id": 1194664677743177729, "media_url": "http://pbs.twimg.com/media/EJRNMd6WsAEs7-e.jpg", "media_url_http

In [130]:
# creating a mapping of users we need to query the api for - going to see if they are connected
userFriendshipMapping = []

for user in users:
    for user2 in users:
        if user != user2:
            if user < user2:
                if [user, user2] not in userFriendshipMapping:
                    userFriendshipMapping.append([user, user2])
            else:
                if [user2, user] not in userFriendshipMapping:
                    userFriendshipMapping.append([user2, user])

for mapping in userFriendshipMapping:
    print(mapping)

print(len(userFriendshipMapping))

[813286, 21447363]
[813286, 27260086]
[813286, 79293791]
[813286, 17919972]
[813286, 155659213]
[813286, 14230524]
[813286, 15846407]
[813286, 34507480]
[813286, 25073877]
[813286, 26565946]
[813286, 25365536]
[813286, 23375688]
[813286, 16409683]
[813286, 44409004]
[21447363, 27260086]
[21447363, 79293791]
[17919972, 21447363]
[21447363, 155659213]
[14230524, 21447363]
[15846407, 21447363]
[21447363, 34507480]
[21447363, 25073877]
[21447363, 26565946]
[21447363, 25365536]
[21447363, 23375688]
[16409683, 21447363]
[21447363, 44409004]
[27260086, 79293791]
[17919972, 27260086]
[27260086, 155659213]
[14230524, 27260086]
[15846407, 27260086]
[27260086, 34507480]
[25073877, 27260086]
[26565946, 27260086]
[25365536, 27260086]
[23375688, 27260086]
[16409683, 27260086]
[27260086, 44409004]
[17919972, 79293791]
[79293791, 155659213]
[14230524, 79293791]
[15846407, 79293791]
[34507480, 79293791]
[25073877, 79293791]
[26565946, 79293791]
[25365536, 79293791]
[23375688, 79293791]
[16409683, 79293

In [137]:
friendshipResults = []

for user1, user2 in userFriendshipMapping:
    relationship = api.ShowFriendship(source_user_id=user1, target_user_id=user2)
    friendshipResults.append(relationship)
    print(relationship)
    print("retrieved friendship information for -> " + str(user1) + "  --  " + str(user2))
    print("waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...")
    time.sleep(65)
    
# checks the friendship between two users
#print(api.ShowFriendship(source_user_id=27260086, target_user_id=23375688))

{'relationship': {'source': {'id': 813286, 'id_str': '813286', 'screen_name': 'BarackObama', 'following': False, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 21447363, 'id_str': '21447363', 'screen_name': 'katyperry', 'following': False, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 813286  --  21447363
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 813286, 'id_str': '813286', 'screen_name': 'BarackObama', 'following': False, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': Non

{'relationship': {'source': {'id': 813286, 'id_str': '813286', 'screen_name': 'BarackObama', 'following': False, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 16409683, 'id_str': '16409683', 'screen_name': 'britneyspears', 'following': False, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 813286  --  16409683
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 813286, 'id_str': '813286', 'screen_name': 'BarackObama', 'following': False, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag':

{'relationship': {'source': {'id': 21447363, 'id_str': '21447363', 'screen_name': 'katyperry', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 23375688, 'id_str': '23375688', 'screen_name': 'selenagomez', 'following': True, 'followed_by': True, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 21447363  --  23375688
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 16409683, 'id_str': '16409683', 'screen_name': 'britneyspears', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag

{'relationship': {'source': {'id': 23375688, 'id_str': '23375688', 'screen_name': 'selenagomez', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 27260086, 'id_str': '27260086', 'screen_name': 'justinbieber', 'following': True, 'followed_by': True, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 23375688  --  27260086
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 16409683, 'id_str': '16409683', 'screen_name': 'britneyspears', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_

{'relationship': {'source': {'id': 16409683, 'id_str': '16409683', 'screen_name': 'britneyspears', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 79293791, 'id_str': '79293791', 'screen_name': 'rihanna', 'following': True, 'followed_by': True, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 16409683  --  79293791
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 44409004, 'id_str': '44409004', 'screen_name': 'shakira', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': Non

{'relationship': {'source': {'id': 14230524, 'id_str': '14230524', 'screen_name': 'ladygaga', 'following': False, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 155659213, 'id_str': '155659213', 'screen_name': 'Cristiano', 'following': True, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 14230524  --  155659213
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 15846407, 'id_str': '15846407', 'screen_name': 'TheEllenShow', 'following': True, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_media_

{'relationship': {'source': {'id': 14230524, 'id_str': '14230524', 'screen_name': 'ladygaga', 'following': False, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 26565946, 'id_str': '26565946', 'screen_name': 'jtimberlake', 'following': True, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 14230524  --  26565946
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 14230524, 'id_str': '14230524', 'screen_name': 'ladygaga', 'following': False, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_media_tag'

{'relationship': {'source': {'id': 25073877, 'id_str': '25073877', 'screen_name': 'realDonaldTrump', 'following': False, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 34507480, 'id_str': '34507480', 'screen_name': 'ArianaGrande', 'following': False, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 25073877  --  34507480
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 26565946, 'id_str': '26565946', 'screen_name': 'jtimberlake', 'following': True, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can

{'relationship': {'source': {'id': 23375688, 'id_str': '23375688', 'screen_name': 'selenagomez', 'following': False, 'followed_by': True, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': True, 'can_media_tag': None, 'blocking': None, 'blocked_by': None, 'muting': None, 'want_retweets': None, 'all_replies': None, 'marked_spam': None}, 'target': {'id': 26565946, 'id_str': '26565946', 'screen_name': 'jtimberlake', 'following': True, 'followed_by': False, 'following_received': None, 'following_requested': None}}}
retrieved friendship information for -> 23375688  --  26565946
waiting for 65 seconds to avoid 15 calls per 15 minutes rate limit...
{'relationship': {'source': {'id': 16409683, 'id_str': '16409683', 'screen_name': 'britneyspears', 'following': False, 'followed_by': False, 'live_following': False, 'following_received': None, 'following_requested': None, 'notifications_enabled': None, 'can_dm': False, 'can_me

In [171]:
# building the relationships with our data

# the relationship object has
# id/screen name,
# following - meaning following the other user, and
# followed by - meaning followed by the other user

# ready our edge list
edgeList = []

# add initial nodes
[edgeList.append([userScreenNamesToIndex[u.screen_name], userScreenNamesToIndex[u.screen_name], 0]) for u in fullUsers]

for dict in friendshipResults:
    friendship = dict["relationship"]
    sourceScreenName = friendship["source"]["screen_name"]
    targetScreenName = friendship["target"]["screen_name"]
    sourceFollowingTarget = 0
    targetFollowingSource = 0
    resultString = "source id: " + friendship["source"]["id_str"] + " screenName: " + friendship["source"]["screen_name"]
    if friendship["source"]["following"]:
        resultString += " is following "
        sourceFollowingTarget = 1
    else:
        resultString += " is not following "
    resultString += " target id: " + friendship["target"]["id_str"] + " screenName: " + friendship["target"]["screen_name"]
    print(resultString)
    resultString = "target id: " + friendship["target"]["id_str"] + " screenName: " + friendship["target"]["screen_name"]
    if friendship["target"]["following"]:
        resultString += " is following "
        targetFollowingSource = 1
    else:
        resultString += " is not following "
    resultString += " source id: " + friendship["source"]["id_str"] + " screenName: " + friendship["source"]["screen_name"]
    print(resultString)
    print()
    edgeList.append([userScreenNamesToIndex[sourceScreenName], userScreenNamesToIndex[targetScreenName], sourceFollowingTarget])
    edgeList.append([userScreenNamesToIndex[targetScreenName], userScreenNamesToIndex[sourceScreenName], targetFollowingSource])

source id: 813286 screenName: BarackObama is not following  target id: 21447363 screenName: katyperry
target id: 21447363 screenName: katyperry is not following  source id: 813286 screenName: BarackObama

source id: 813286 screenName: BarackObama is not following  target id: 27260086 screenName: justinbieber
target id: 27260086 screenName: justinbieber is following  source id: 813286 screenName: BarackObama

source id: 813286 screenName: BarackObama is not following  target id: 79293791 screenName: rihanna
target id: 79293791 screenName: rihanna is not following  source id: 813286 screenName: BarackObama

source id: 813286 screenName: BarackObama is not following  target id: 17919972 screenName: taylorswift13
target id: 17919972 screenName: taylorswift13 is not following  source id: 813286 screenName: BarackObama

source id: 813286 screenName: BarackObama is not following  target id: 155659213 screenName: Cristiano
target id: 155659213 screenName: Cristiano is not following  source id:

In [172]:
for edge in edgeList:
    print(edge)

[0, 0, 0]
[1, 1, 0]
[2, 2, 0]
[3, 3, 0]
[4, 4, 0]
[5, 5, 0]
[6, 6, 0]
[7, 7, 0]
[8, 8, 0]
[9, 9, 0]
[10, 10, 0]
[11, 11, 0]
[12, 12, 0]
[13, 13, 0]
[14, 14, 0]
[0, 1, 0]
[1, 0, 0]
[0, 2, 0]
[2, 0, 1]
[0, 3, 0]
[3, 0, 0]
[0, 4, 0]
[4, 0, 0]
[0, 5, 0]
[5, 0, 0]
[0, 6, 0]
[6, 0, 1]
[0, 7, 0]
[7, 0, 1]
[0, 8, 0]
[8, 0, 1]
[0, 9, 0]
[9, 0, 0]
[0, 10, 0]
[10, 0, 1]
[0, 11, 0]
[11, 0, 1]
[0, 12, 0]
[12, 0, 0]
[0, 13, 0]
[13, 0, 0]
[0, 14, 0]
[14, 0, 1]
[1, 2, 0]
[2, 1, 1]
[1, 3, 1]
[3, 1, 1]
[4, 1, 0]
[1, 4, 1]
[1, 5, 0]
[5, 1, 0]
[6, 1, 1]
[1, 6, 1]
[7, 1, 1]
[1, 7, 1]
[1, 8, 1]
[8, 1, 1]
[1, 9, 0]
[9, 1, 0]
[1, 10, 0]
[10, 1, 0]
[1, 11, 0]
[11, 1, 0]
[1, 12, 1]
[12, 1, 1]
[13, 1, 1]
[1, 13, 1]
[1, 14, 0]
[14, 1, 0]
[2, 3, 1]
[3, 2, 0]
[4, 2, 0]
[2, 4, 0]
[2, 5, 1]
[5, 2, 1]
[6, 2, 0]
[2, 6, 1]
[7, 2, 1]
[2, 7, 1]
[2, 8, 1]
[8, 2, 1]
[9, 2, 0]
[2, 9, 0]
[10, 2, 1]
[2, 10, 1]
[11, 2, 0]
[2, 11, 1]
[12, 2, 1]
[2, 12, 1]
[13, 2, 1]
[2, 13, 1]
[2, 14, 1]
[14, 2, 0]
[4, 3, 0]
[3, 4, 0]
[3, 5, 1]


In [175]:
import numpy as np

n = max(max(user1 + 1, user2 + 1) for user1, user2, following in edgeList) # Get size of matrix
matrix = np.zeros((n, n))
for user1, user2, following in edgeList:
    matrix[user1][user2] = following # Convert to 0-based index.

# the meaning is the row index vs the column index --- row-user following the column-user / true or false
for row in matrix:
    print(row)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0.]
[1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
[0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
[1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0.]
[1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0.]
[1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [190]:
rows = []

firstRow = ""
for user in userIntToScreenNames:
    firstRow += "," + user

rows.append(firstRow)

i = 0
for row in matrix:
    rowString = userIntToScreenNames[i]
    for element in row:
        rowString += "," + str(int(element))
    rows.append(rowString)
    i += 1

# rows are built for csv, time to write them
f = open("twitter_relationships.csv", "+a")
for row in rows:
    f.write(row + "\n")

f.close()